### PR TITLE
Brought all third party dependencies into the project and updated refs

### PR DESCRIPTION
**Pull request by jrdan**
This removes our reliance on third party CDNs that could effect the Cortex's accessiblity should the CDNs become unavailable/inaccessible.

### CODE REVIEW

**Comment by claytonpeters** [comment]
I think we're missing a font or something here - the sorting arrows on DataTables aren't showing correctly.

**Comment by jakemalley** [comment]
That's weird because they show up when the dark theme is enabled.

**Comment by claytonpeters** [comment]
So they do... That's odd. I thought that was all handled by the DataTables CSS which doesn't change on the theme. Maybe it's in the bootstrap theme somewhere.

**Comment by claytonpeters** [comment]
Ah there we go, bootstrap-dark.css is still pulling them in from netdna.

**Comment by claytonpeters** [comment]
Also, bootstrap is still pulling in fonts from fonts.gstatic.com. Welcome to the rabbit-hole we hit when we last tried this :P

**Comment by jakemalley** [comment]
I was just about to comment about this haha, just download a local copy of the internet for us to use.

**Comment by claytonpeters** [comment]
Ok, I think I've sorted most of these on Jordan's dev box now. Not committed yet though,

**Pull request merged**
