### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by claytonpeters**

### CODE REVIEW

**Comment by claytonpeters** [comment]
I'm making a couple of changes to the workflow locking as I spotted a bug. I'll double fix those duplicate conditions too.

**Comment by claytonpeters** [comment]
Found another bug - StrictRedis returns bytes objects so the "notify in ['done']" thing that we do when waiting for the installer to finish is broken. Just fixing that.

**Comment by jakemalley** [comment]
we need some unit tests lol

**Comment by claytonpeters** [comment]
This has very much crossed my mind today as I've tested pretty much every part by hand. This is sort of what the new more-isolated dev environment was built for though!

**Comment by claytonpeters** [comment]
It's taken me almost all day of testing and fixing, but I think this is now all working.

**Comment by jakemalley** [comment]
I ran the code through python-modernize (more out of curiosity), and have fixed the last remaining thing.

Would it be sensible to hold off on merging this into v4-fixes; finishing other added features (i.e. all other branches open except `vmcharging`) pulling them into this branch - fix the python 2/3 issues. Then merge this into a new `v5` branch?

**Comment by claytonpeters** [comment]
I need to get a release out before the end of the month, so I think I'll merge in the Rubrik stuff as that looks relatively ready to go, and if we get the VM charging thing looked at I'll merge that in too,

**Comment by jakemalley** [comment]
VM Charging isn't really finished yet anyway - unless its required I wouldn't bother - we can always do another realise in Sep/Oct.

**Pull request merged**
